export const SEARCH_START = "SEARCH_START";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAILURE = "SEARCH_FAILURE";

export const FETCH_INFO_USER_START = "FETCH_INFO_USER_START";
export const FETCH_INFO_USER_SUCCESS = "FETCH_INFO_USER_SUCCESS";
export const FETCH_INFO_USER_FAILURE = "FETCH_INFO_USER_FAILURE";

export const FETCH_INFO_ORG_START = "FETCH_INFO_ORG_START";
export const FETCH_INFO_ORG_SUCCESS = "FETCH_INFO_ORG_SUCCESS";
export const FETCH_INFO_ORG_FAILURE = "FETCH_INFO_ORG_FAILURE";
