export const SEARCH_START = "SEARCH_START";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAILURE = "SEARCH_FAILURE";

export const SHOW_PAGE_START = "SHOW_PAGE_START";
export const SHOW_PAGE_SUCCESS = "SHOW_PAGE_SUCCESS";
export const SHOW_PAGE_FAILURE = "SHOW_PAGE_FAILURE";
